### ISSUE TITLE
Really like the idea, how can I help? Do you have sources for getting to know WebGL a little better?

### ISSUE THREAD

**Issue by Flyrell** [Rich-Harris/svelte-gl#5]
Idea seems great. I've been working with a lot of Three.js lately and I had thought about doing/using something like this. Also saw your talk and blogs on Svelte, great work! Hope I'll be able to help on that one too, but first I'm gonna try it as I didn't have a chance yet 😜 

Well, now to the point. I haven't worked with a "raw" WebGL code yet. You have any sources where I could get the most information which are well-described? I mean, [WebGL Specs](https://www.khronos.org/registry/webgl/specs/1.0/) are not the worst one, but I was thinking maybe something a little more interactive for the beginning. Thanks.

**Comment by saabi** [comment]
If you're not familiar with OpenGL then I suggest you take a look at some primers. There's lots of stuff on the web.

The *official* one: https://www.khronos.org/webgl/wiki/Tutorial
WebGL fundamentals: https://webglfundamentals.org/webgl/lessons/webgl-fundamentals.html
Mozilla's tutorial: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Getting_started_with_WebGL

They're all quite similar, but the final choice is probably subjective.

**Comment by Flyrell** [comment]
Sorry @saabi I must have missed your answer. Thanks for the tips, I'll surely give them a look.
