### ISSUE TITLE
Check this out!

### ISSUE THREAD

**Issue by levitabris** [Rich-Harris/svelte-gl#7]
Hi All,

I found [A-Frame](https://aframe.io/docs/1.0.0/introduction/) to be a very similar idea. And it is well implemented already. Any thoughts? I haven't tested any integration compatibilities though. But the API looks svelty!

```
<html>
  <head>
    <script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
  </head>
  <body>
    <a-scene>
      <a-box position="-1 0.5 -3" rotation="0 45 0" color="#4CC3D9"></a-box>
      <a-sphere position="0 1.25 -5" radius="1.25" color="#EF2D5E"></a-sphere>
      <a-cylinder position="1 0.75 -3" radius="0.5" height="1.5" color="#FFC65D"></a-cylinder>
      <a-plane position="0 0 -4" rotation="-90 0 0" width="4" height="4" color="#7BC8A4"></a-plane>
      <a-sky color="#ECECEC"></a-sky>
    </a-scene>
  </body>
</html>
```

Regards,
Wei

**Comment by levitabris** [comment]
I was already noticed by the sveltjs account here: 
https://github.com/sveltejs/gl

**Comment by mootari** [comment]
It's also leading the third paragraph of this repo's readme. ;)
